version: "3.9"

services:
  websocket:
    build: ./websocket-api
    ports:
      - "3000:3000"
    env_file:
      - ./websocket-api/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - REACT_APP_WS_URL=http://websocket:3000
    depends_on:
      - websocket
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
